# Generated by Django 3.0.3 on 2020-05-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('tz', models.CharField(max_length=250)),
                ('activity_periods', models.CharField(max_length=250)),
            ],
        ),
    ]
