# Generated by Django 3.0.3 on 2020-05-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0002_auto_20200505_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullThrottle_User',
            new_name='UserData',
        ),
    ]
