# Generated by Django 3.0.3 on 2020-05-05 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0003_auto_20200505_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='activity_periods',
        ),
        migrations.AddField(
            model_name='userdata',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
