# Generated by Django 3.0.3 on 2020-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0004_auto_20200505_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
