# Generated by Django 3.0.3 on 2020-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0005_auto_20200505_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='start_time',
        ),
    ]
