# Generated by Django 3.0.3 on 2020-05-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0007_auto_20200505_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={'verbose_name': 'timeStamp'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'UserData'},
        ),
    ]
