# Generated by Django 3.0.3 on 2020-05-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0008_auto_20200506_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
    ]
