# Generated by Django 3.0.3 on 2020-05-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0009_auto_20200506_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='tz',
            new_name='user_id',
        ),
    ]
