# Generated by Django 3.0.3 on 2020-05-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0010_auto_20200506_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='user_id',
            new_name='_id',
        ),
    ]
